[package]
name = "simple-router-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
axum-extra = "0.9.2"
futures-executor = "0.3.30"
http = "1.0.0"
tower-service = "0.3.2"
