#!/usr/bin/env python
# -*- coding:utf-8 -*-

"""
Topic: python flask框架的一个简单的  首页-》 登录页-》 登录成功页
Desc: 首页：http://localhost:8000/
      登录页：http://localhost:8000/signin
             登录名：admin
             密  码：admin
            登录成功后返回：登录成功信息
"""

from flask import Flask
from flask import request

app = Flask(__name__)
@app.route('/',methods=['GET','POST'])
def home():
    return '<h1>Home</h1>'

@app.route('/signin',methods=['GET'])
def signin_form():
    return  '''
    <form action="/signin" method="post">
    <p><input name="username"></p>
    <p><input name="password" type="password"></p>
    <p><button type="submint">Sign In</button></p>
    </form
    '''

@app.route('/signin',methods=['POST'])
def signin():
    # 需要从request对象读取表单内容：
    if request.form['username'] =='admin' and request.form['password']=='admin':
        return '<h3>Hello, admin!</h3>'
    return '<h3>Bad username or password.</h3>'

if __name__=='__main__':
    app.run()
