[package]
name = "books"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "7.0.2"
async-stream = "0.3.5"
futures-channel = "0.3.30"
futures-timer = "3.0.2"
futures-util = "0.3.30"
once_cell = "1.19.0"
slab = "0.4.9"
