name: test_dart
description: >-
  This is an exerices project for learning the dart langage.
auth: bodii
version: 0.0.1
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  dio: ">=4.0.6 <6.0.0"
  http: ^0.13.4
dev_dependencies:
  test: '>=1.15.0 <2.0.0'

