version: 1
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: basic
  audit_file:
    class: logging.FileHandler
    filename: p3_c14_audit.log
    encoding: utf-8
    formatter: detailed
formatters:
  basic:
    style: '{'
    format: '{levelname:s}:{name:s}:{message:s}'
  detailed:
    style: '{'
    format: '{levelname:s}:{name:s}:{asctime:s}:{message:s}'
    datefmt: '%Y-%m-%d %H:%M:%S'
loggers:
  audit:
    handlers: [console, audit_file]
    levle: INFO
    propagate: TRUE
  root:
    handlers: [console]
    level: INFO
