[package]
name = "subscription"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "7.0.2"
async-graphql-axum = "7.0.2"
axum = { version = "0.7.4", features = ["ws"] }
books = { version = "0.1.0", path = "../models/books" }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
